//Guess the number Game

const prompt = require('prompt-sync')({ sigint: true });

let rand_num = Math.ceil(Math.random() * 100)
let chances = 0;
let i = 0;
while (i < 100) {
    let user_num = prompt("Enter a number:- ");
    user_num = Number.parseInt(user_num);
    if (rand_num > user_num) {
        console.log("The number enterd is lesser than the actual number\n");
    } else if (rand_num < user_num) {
        console.log("The number enterd is greater than the actual number\n");
    } else if (rand_num == user_num) {
        console.log("Congratulations! The number is ", rand_num);
        break;
    } else {
        console.error("Enter a valid number\n");
    }
    chances++;
}
console.log(`You got the number in ${chances} chances. Your score is ${100 - chances}`);



/*
let number = Math.floor((Math.random() * 100) + 1); // Generates a random number b/w 1 and 100
let chances = 0; // Initial vaulue of chances taken to guess a number
let guess; // Variable to store the number to be input from user to be guessed

console.log("This is a guessing game and you have to enter a number and if it matches with the number generated by computer, then you win...\n");
guess = prompt("Enter a number between 1 and 100");
++chances; // To increment the number of chances taken

do {
  guess = Number.parseInt(guess);

  if (guess > number) {
    console.log("Number entered is greater");
    guess = prompt("Enter again!!");
    guess = Number.parseInt(guess);
    ++chances; // To increment the number of chances taken
    continue;
  }

  else if (guess < number) {
    console.log("Number entered is smaller");
    guess = prompt("Enter again!!");
    guess = Number.parseInt(guess);
    ++chances; //To increment the number of chances taken
    continue;
  }

} while (guess != number); //break the loop if number entered is equal to the number generated

let score = 100 - chances; //To store the score of your game
console.log("\nCongratulations🥳🥳\nThe number generated was", number + " and you guessed it right😁\nYour final score is", score);
*/